In [1]:
import tensorflow as tf
import numpy as np
from tensorflow.python.framework import ops

In [2]:
data_size = 25
data_1d = np.random.normal(size=data_size)

In [3]:
x_input_1d = tf.placeholder(dtype=tf.float32, shape=[data_size])

In [4]:
def conv_layer_1d(input_1d, my_filter):
    input_2d = tf.expand_dims(input_1d, 0)
    input_3d = tf.expand_dims(input_2d, 0)
    input_4d = tf.expand_dims(input_3d, 3)
    convolution_output = tf.nn.conv2d(input_4d, filter=my_filter, strides=[1, 1, 1, 1], padding="VALID")
    conv_output_1d = tf.squeeze(convolution_output)
    return conv_output_1d

my_filter_1d = tf.Variable(tf.random_normal(shape=[1, 5, 1, 1]))
my_convolution_output_1d = conv_layer_1d(x_input_1d, my_filter_1d)

In [5]:
def activation_1d(input_1d):
    return tf.nn.relu(input_1d)

my_activation_output_1d = activation_1d(my_convolution_output_1d)

In [6]:
def max_pool_1d(input_1d, width):
    input_2d = tf.expand_dims(input_1d, 0)
    input_3d = tf.expand_dims(input_2d, 0)
    input_4d = tf.expand_dims(input_3d, 3)
    pool_output = tf.nn.max_pool(input_4d, ksize=[1, 1, width, 1], strides=[1, 1, 1, 1], padding="VALID")
    pool_output_1d = tf.squeeze(pool_output)
    return pool_output_1d

my_maxpool_output_1d = max_pool_1d(my_activation_output_1d, width=5)

In [7]:
def fully_connected_1d(input_layer, num_outputs):
    weight_shape = tf.squeeze(tf.stack(
        [tf.shape(input_layer), [num_outputs]]))
    weight = tf.random_normal(weight_shape, stddev=0.1)
    bias = tf.random_normal(shape=[num_outputs])
    input_layer_2d = tf.expand_dims(input_layer, 0)
    full_output = tf.add(tf.matmul(input_layer_2d, weight), bias)
    full_output_1d = tf.squeeze(full_output)
    return full_output_1d

my_full_output_1d = fully_connected_1d(my_maxpool_output_1d, 5)

In [8]:
with tf.Session() as sess:
    bs = 25
    data_1d = np.random.normal(size=data_size)
    init = tf.global_variables_initializer()
    sess.run(init)
    feed_dict = {x_input_1d: data_1d}
    
    print('Input = array of length 25')
    print('Convolution w/filter, length = 5, stride size = 1, '
          'results in an array of length 21:')
    print(sess.run(my_convolution_output_1d, feed_dict=feed_dict))
    print('\nInput = the above array of length 21')
    print('ReLU element wise returns the array of length 21:')
    print(sess.run(my_activation_output_1d, feed_dict=feed_dict))
    print('\nInput = the above array of length 21')
    print('MaxPool, window length = 5, stride size = 1, '
          'results in the array of length 17')
    print(sess.run(my_maxpool_output_1d, feed_dict=feed_dict))
    print('\nInput = the above array of length 17')
    print('Fully connected layer on all four rows with five outputs:')
    print(sess.run(my_full_output_1d, feed_dict=feed_dict))

Input = array of length 25
Convolution w/filter, length = 5, stride size = 1, results in an array of length 21:
[-2.453808   -0.30292547 -0.78732765 -0.12066847  1.096965    0.48903883
  1.3645414  -0.22699374  0.97743744 -1.1542246   0.7699039   0.26018286
  1.4030986  -1.3333541   0.6426519   0.44966814  0.35361156  1.2213199
 -1.8093159  -1.2578562  -0.46365836]

Input = the above array of length 21
ReLU element wise returns the array of length 21:
[0.         0.         0.         0.         1.096965   0.48903883
 1.3645414  0.         0.97743744 0.         0.7699039  0.26018286
 1.4030986  0.         0.6426519  0.44966814 0.35361156 1.2213199
 0.         0.         0.        ]

Input = the above array of length 21
MaxPool, window length = 5, stride size = 1, results in the array of length 17
[1.096965   1.096965   1.3645414  1.3645414  1.3645414  1.3645414
 1.3645414  0.97743744 1.4030986  1.4030986  1.4030986  1.4030986
 1.4030986  1.2213199  1.2213199  1.2213199  1.2213199 ]

In

In [15]:
ops.reset_default_graph()
data_size = [10, 10]
data_2d = np.random.normal(size=data_size)
x_input_2d = tf.placeholder(dtype=tf.float32, shape=data_size)

In [16]:
def conv_layer_2d(input_2d, my_filter):
    input_3d = tf.expand_dims(input_2d, 0)
    input_4d = tf.expand_dims(input_3d, 3)
    convolution_output = tf.nn.conv2d(input_4d, filter=my_filter, strides=[1, 2, 2, 1], padding="VALID")
    conv_output_2d = tf.squeeze(convolution_output)
    return conv_output_2d

my_filter_2d = tf.Variable(tf.random_normal(shape=[2, 2, 1, 1]))
my_convolution_output_2d = conv_layer_2d(x_input_2d, my_filter_2d)

In [17]:
def activation_2d(input_2d):
    return tf.nn.relu(input_2d)

my_activation_output_2d = activation_2d(my_convolution_output_2d)

In [18]:
def max_pool_2d(input_2d, width, height):
    input_3d = tf.expand_dims(input_2d, 0)
    input_4d = tf.expand_dims(input_3d, 3)
    pool_output = tf.nn.max_pool(input_4d, ksize=[1, height, width, 1], strides=[1, 1, 1, 1], padding="VALID")
    pool_output_2d = tf.squeeze(pool_output)
    return pool_output_2d

my_maxpool_output_2d = max_pool_2d(my_activation_output_2d, width=2, height=2)

In [19]:
def fully_connected_2d(input_layer, num_outputs):
    flat_input = tf.reshape(input_layer, [-1])
    weight_shape = tf.squeeze(tf.stack(
        [tf.shape(flat_input), [num_outputs]]))
    weight = tf.random_normal(weight_shape, stddev=0.1)
    bias = tf.random_normal(shape=[num_outputs])
    input_layer_2d = tf.expand_dims(flat_input, 0)
    full_output = tf.add(tf.matmul(input_layer_2d, weight), bias)
    full_output_2d = tf.squeeze(full_output)
    return full_output_2d

my_full_output_2d = fully_connected_2d(my_maxpool_output_2d, 5)

In [20]:
with tf.Session() as sess:
    init = tf.global_variables_initializer()
    sess.run(init)
    feed_dict = {x_input_2d: data_2d}
    
    print('Input = [10, 10] array')
    print('[2, 2] Convolution, stride size = [2, 2], '
          'results in the [5, 5] array')
    print(sess.run(my_convolution_output_2d, feed_dict=feed_dict))
    print('\nInput = the above [5, 5] array')
    print('ReLU element wise returns the [5, 5] array')
    print(sess.run(my_activation_output_2d, feed_dict=feed_dict))
    print('\nInput = the above [5, 5]array')
    print('MaxPool, stride size = [1, 1], '
          'results in the [4, 4] array')
    print(sess.run(my_maxpool_output_2d, feed_dict=feed_dict))
    print('\nInput = the above [4, 4] array')
    print('Fully connected layer on all four rows with five outputs:')
    print(sess.run(my_full_output_2d, feed_dict=feed_dict))

Input = [10, 10] array
[2, 2] Convolution, stride size = [2, 2], results in the [5, 5] array
[[ 2.436744    1.5442536   2.332376    0.04886294 -0.7926846 ]
 [ 1.3266189  -1.0789306   0.88776016 -2.386244   -0.20309585]
 [-1.8694111   2.5450678  -0.3218176  -1.110787    0.27509728]
 [-0.60600936  1.4475003  -1.5691186   1.2776353  -3.5035255 ]
 [ 0.9595084  -2.6093416  -1.0785704  -1.8451105   1.617766  ]]

Input = the above [5, 5] array
ReLU element wise returns the [5, 5] array
[[2.436744   1.5442536  2.332376   0.04886294 0.        ]
 [1.3266189  0.         0.88776016 0.         0.        ]
 [0.         2.5450678  0.         0.         0.27509728]
 [0.         1.4475003  0.         1.2776353  0.        ]
 [0.9595084  0.         0.         0.         1.617766  ]]

Input = the above [5, 5]array
MaxPool, stride size = [1, 1], results in the [4, 4] array
[[2.436744   2.332376   2.332376   0.04886294]
 [2.5450678  2.5450678  0.88776016 0.27509728]
 [2.5450678  2.5450678  1.2776353  1.2776